services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: backend
    depends_on:
      - mongodb
      - db-init
      - data-pipeline
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/home_dashboard
      - DATA_PIPELINE_URL=http://10.0.0.26:3001/
  
  data-pipeline:
    build:
      context: ./data-pipeline
    container_name: data-pipeline
    depends_on:
      - mongodb
    volumes:
      - msft_token_data:/app/msft_helper/api_token
    ports:
      - "3001:3001"
    environment:
      - PORT=3001

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://10.0.0.26:3000/api
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"

  db-init:
    build:
      context: ./db-init
    container_name: db-init
    depends_on:
      - mongodb
    restart: "no"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/home_dashboard

volumes:
  mongodb_data:
  msft_token_data:
